.TH "src Directory Reference" 3 "Wed May 19 2021" "Version 1.0" "Projeto II" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmain\&.cpp\fP"
.br
.RI "Código do programa principal\&. "
.ti -1c
.RI "file \fBtrie\&.h\fP"
.br
.RI "Código da trie\&. "
.ti -1c
.RI "file \fBtrie\&.inc\fP"
.br
.in -1c
