.TH "src/main.cpp" 3 "Wed May 19 2021" "Version 1.0" "Projeto II" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main.cpp \- Código do programa principal\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <fstream>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <typeinfo>\fP
.br
\fC#include <tuple>\fP
.br
\fC#include 'trie\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.RI "Programa principal, realiza a leitura e processamento dos dicionários e indica o que as palavras da entrada são, se a palavra pertence ao dicionário é impresso a sua posição e o comprimeto da linha em que a palavra está\&. "
.in -1c
.SH "Detailed Description"
.PP 
Código do programa principal\&. 


.PP
\fBAuthor\fP
.RS 4
Rafael Nilson Witt 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate\fP
.RS 4
2021-05-05
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2021 
.RE
.PP

.PP
Definition in file \fBmain\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main ()"

.PP
Programa principal, realiza a leitura e processamento dos dicionários e indica o que as palavras da entrada são, se a palavra pertence ao dicionário é impresso a sua posição e o comprimeto da linha em que a palavra está\&. 
.PP
Definition at line 26 of file main\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Projeto II from the source code\&.
